version: "3.9"

networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  ubuntu:
    image: ubuntu
    container_name: ubuntu_static
    command: sleep infinity
    networks:
      my_network:
        ipv4_address: 192.168.1.100

